repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        entry: uv run shfmt -w -i 2 -ci -bn
        language: system
        types: [shell]
      - id: shellcheck
        name: shellcheck
        entry: bash scripts/run_shellcheck.sh
        language: system
        types: [shell]
